[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
richie = "5WZ32L1T2Em5zFzF4NpFq8VX6NxfvAzHWgr7Zkqci37R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/kartos.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
