[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
richie = "13PntzJFX9da8hCrAmB9q5HcMYfPeQ4HMYcNU56qqBrF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/kartos.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
